# Workflow to fun all pycraft2 tox environments against the development Python version.

name: Tox

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get -qqy install tox
    - name: Git checkout
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
    - name: Run tox for Python ${{ matrix.python-version }}
      run: |
        tox
